### ISSUE TITLE
关于启动报错的问题,gradle 和 maven 都报,IllegalAccessError:class com.jfoenix.skins.JFXTabPaneSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module com.jfoenix

### ISSUE THREAD

**Issue by iqolome** [icuxika/JavaFX-Package-Sample#3]
到本

```log
"C:\Program Files\Java\jdk-17.0.1\bin\java.exe" -Dvisualvm.id=89157711033600 "-javaagent:D:\Software\IntelliJ IDEA 2021.3\lib\idea_rt.jar=7442:D:\Software\IntelliJ IDEA 2021.3\bin" -Dfile.encoding=UTF-8 -classpath D:\Server\repository\org\openjfx\javafx-base\17.0.0.1\javafx-base-17.0.0.1.jar;D:\Server\repository\org\openjfx\javafx-controls\17.0.0.1\javafx-controls-17.0.0.1.jar;D:\Server\repository\org\openjfx\javafx-graphics\17.0.0.1\javafx-graphics-17.0.0.1.jar;D:\Server\repository\org\openjfx\javafx-fxml\17.0.0.1\javafx-fxml-17.0.0.1.jar;D:\Server\repository\org\openjfx\javafx-swing\17.0.0.1\javafx-swing-17.0.0.1.jar;D:\Server\repository\org\openjfx\javafx-media\17.0.0.1\javafx-media-17.0.0.1.jar;D:\Server\repository\org\openjfx\javafx-web\17.0.0.1\javafx-web-17.0.0.1.jar -p D:\Server\repository\org\openjfx\javafx-swing\17.0.0.1\javafx-swing-17.0.0.1-win.jar;D:\Server\repository\com\jfoenix\jfoenix\9.0.10\jfoenix-9.0.10.jar;D:\Server\repository\org\openjfx\javafx-web\17.0.0.1\javafx-web-17.0.0.1-win.jar;D:\Server\repository\org\openjfx\javafx-media\17.0.0.1\javafx-media-17.0.0.1-win.jar;D:\Server\repository\org\openjfx\javafx-fxml\17.0.0.1\javafx-fxml-17.0.0.1-win.jar;D:\Server\repository\org\openjfx\javafx-base\17.0.0.1\javafx-base-17.0.0.1-win.jar;D:\workspace\JavaFX-Package-Sample\target\classes;D:\Server\repository\org\openjfx\javafx-controls\17.0.0.1\javafx-controls-17.0.0.1-win.jar;D:\Server\repository\org\openjfx\javafx-graphics\17.0.0.1\javafx-graphics-17.0.0.1-win.jar -m sample/com.icuxika.MainApp
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: class com.jfoenix.skins.JFXTabPaneSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module com.jfoenix
	at com.jfoenix/com.jfoenix.skins.JFXTabPaneSkin.<init>(JFXTabPaneSkin.java:86)
	at com.jfoenix/com.jfoenix.controls.JFXTabPane.createDefaultSkin(JFXTabPane.java:67)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9456)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1774)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1114)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1190)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1205)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
	at sample/com.icuxika.MainApp.start(MainApp.java:31)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more
Exception running application com.icuxika.MainApp

Process finished with exit code 1
```

**Comment by iqolome** [comment]
大佬帮忙看看咋肥四啊
